version: '3'

services:
  master:
#    extra_hosts:
#     - "bienlab.com:192.168.31.4"
    image: biennt/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://vnexpress.net
  
  worker:
#    extra_hosts:
#     - "bienlab.com:192.168.31.4"
    image: biennt/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

